# Generated by Django 2.0 on 2018-03-08 10:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waldmeister_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarea',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name=4326),
        ),
    ]
