# Generated by Django 2.0.5 on 2018-05-22 18:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waldmeister_map', '0002_auto_20180308_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ek72', models.CharField(max_length=10)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
